spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/moviebooking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USER:movie}
spring.datasource.password=${MYSQL_PASSWORD:Nandhini@07}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080

